//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bebida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bebida()
        {
            this.RefeicaoBebidas = new HashSet<RefeicaoBebida>();
        }
    
        public int BebidasID { get; set; }
        public string Categoria { get; set; }
        public string Nome { get; set; }
        public int Unidade { get; set; }
        public double Kcal { get; set; }
        public double Proteinas { get; set; }
        public double Gordura { get; set; }
        public double HidCarbono { get; set; }
        public double HC_Acucar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefeicaoBebida> RefeicaoBebidas { get; set; }
    }
}
