//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiniao
    {
        public int commentID { get; set; }
        public int userID { get; set; }
        public bool Opiniao1 { get; set; }
    
        public virtual Comentario Comentario { get; set; }
    }
}
