//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prato()
        {
            this.RefeicaoPratos = new HashSet<RefeicaoPrato>();
        }
    
        public int PratosID { get; set; }
        public string Nome { get; set; }
        public int Unidade { get; set; }
        public int Kcal { get; set; }
        public int Proteinas { get; set; }
        public int Gordura { get; set; }
        public string Categoria { get; set; }
        public int HC_Acucar { get; set; }
        public double HidCarbono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefeicaoPrato> RefeicaoPratos { get; set; }
    }
}
