//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefeicaoIngrediente
    {
        public int IngredienteID { get; set; }
        public int RefeicaoID { get; set; }
        public int Quantidade { get; set; }
    
        public virtual Refeico Refeico { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
    }
}
